name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [main, dev]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build Angular (production)
        run: npx ng build --configuration production --base-href "/${{ github.event.repository.name }}/"

      - name: SPA fallback (copy index -> 404)
        run: |
          cp dist/ssr-editor-frontend/browser/index.html dist/ssr-editor-frontend/browser/404.html

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/ssr-editor-frontend/browser

